# spring配置
spring:
  application:
    name: quiz
  # 数据源配置
  datasource:
    url: jdbc:mysql://101.34.56.241:3306/quiz
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: U2FsdGVkX1/w
    hikari:
      max-lifetime: 30000
  # redis配置
  redis:
    host: redis-10455.c9.us-east-1-4.ec2.cloud.redislabs.com
    username: default
    password: iMr1NbXlD8HjKWVjJtbDNsXiKT1BaKW8
    port: 10455
    connect-timeout: 10000
    lettuce:
      pool:
        # 开启连接池
        enabled: true
  # security 安全验证 默认的账号密码(重新实现 UserDetailsService 会让配置失效)
  security:
    user:
      name: admin
      password: 123

# 自动生成文档配置
knife4j:
  enable: true # 启用knife4j
  production: false # 是否在生成环境(生产环境无法访问)

# 配置日志
logging:
  config: classpath:log4j2-spring-dev.xml

# 文件上传位置
file:
  dir: D:\temp\upload

