# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 1888
  servlet:
    # 应用的访问路径
    context-path: /

# spring配置
spring:
  profiles:
    active: @activated.profile@

# Mybatis-plus的配置
mybatis-plus:
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath:mappers/**/*.xml

# 微信小程序
wx:
  min-app:
    configs:
      - appid: wx0f4e873ad758a586
        secret: cf5c68b3ff0d85251cfb178d0f9c0025
        msg-data-format: JSON