# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 1888
  servlet:
    # 应用的访问路径
    context-path: /

# spring配置
spring:
  profiles:
    active: @activated.profile@
  # 邮箱配置
  mail:
    #smtp服务主机  qq邮箱则为smtp.qq.com
    host: smtp.163.com
    #服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: 18890176107@163.com
    #授权码
    password: RPZSKFJTGWQNYJLI
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  servlet:
    multipart:
      max-file-size: 10MB  # 设置单个文件的最大大小
      max-request-size: 20MB  # 设置整个请求的最大大小

# Mybatis-plus的配置
mybatis-plus:
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath:mappers/**/*.xml

# 微信小程序
wx:
  min-app:
    configs:
#      - appid: wx0f4e873ad758a586
#        secret: cf5c68b3ff0d85251cfb178d0f9c0025
#        msg-data-format: JSON
      - appid: wxf2f9d21291120320
        secret: fd6a2a284d6fe7a520bec312d0408d0d
        msg-data-format: JSON