# spring配置
spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/quiz
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: U2FsdGVkX1/w
    hikari:
      max-lifetime: 30000
  # redis配置
  redis:
    host: 127.0.0.1
    username:
    password:
    port: 6379
    connect-timeout: 10000
    lettuce:
      pool:
        # 开启连接池
        enabled: true
  # security 安全验证 默认的账号密码(重新实现 UserDetailsService 会让配置失效)
  security:
    user:
      name: admin
      password: 123

# 自动生成文档配置
knife4j:
  enable: true # 启用knife4j
  production: true # 是否在生成环境(生产环境无法访问)

# 配置日志
logging:
  config: classpath:log4j2-spring-prod.xml

# 文件上传位置
file:
  dir: /var/tmp/quiz
