# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 1888
  servlet:
    # 应用的访问路径
    context-path: /

# spring配置
spring:
  application:
    name: quiz
  # 数据源配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/quiz
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    hikari:
      max-lifetime: 30000
  # redis配置
  redis:
    host: redis-10455.c9.us-east-1-4.ec2.cloud.redislabs.com
    username: default
    password: iMr1NbXlD8HjKWVjJtbDNsXiKT1BaKW8
    port: 10455
    connect-timeout: 10000
    lettuce:
      pool:
        # 开启连接池
        enabled: true
  # security 安全验证 默认的账号密码(重新实现 UserDetailsService 会让配置失效)
  security:
    user:
      name: admin
      password: 123

# Mybatis-plus的配置
mybatis-plus:
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath:mappers/**/*.xml

# 自动生成文档配置
knife4j:
  enable: true # 启用knife4j
  production: false # 是否在生成环境(生产环境无法访问)

# 配置日志
logging:
  level:
    root: INFO #日志级别
    sql: INFO
    com.quiz: DEBUG

# 微信小程序
wx:
  min-app:
    configs:
      - appid: wx0f4e873ad758a586
        secret: cf5c68b3ff0d85251cfb178d0f9c0025
        msg-data-format: JSON

